spring:
  datasource:
    username: root
    password: root123
    url: jdbc:mysql://47.105.213.66:3306/SLDJ?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

#uploadFile
fileUpload:
  path: /home/static/image/
